#!/bin/bash
## makes PKGUILD and builds it (without root access), then installs it (prompts for password if necessary)
set -e

initPwd=$PWD

pyPkg=
pyCmd=
for minor in 6 5 4 3 2 ; do
	cmd="/usr/bin/python3.$minor"
	if [ -f "$cmd" ] ; then
		pyPkg="python3$minor"
		pyCmd="$cmd"
		break
	fi
done
if [ -z "$pyPkg" ] ; then
	echo "Please install python3.6 and try again" >&2
	exit 1
fi
echo "Using python package \"$pyPkg\""

myPath="$0"
if [ "${myPath:0:2}" == "./" ] ; then
	myPath=$initPwd${myPath:1}
elif [ "${myPath:0:1}" != "/" ] ; then
	myPath=$initPwd/$myPath
fi


pkgName=starcal3
sourceDir="`dirname \"$myPath\"`"
#"$sourceDir/scripts/assert_python3"
version=`"$sourceDir/scal3/get_version.py" | sed 's/\-/_/g'`

tmpDir="$HOME/.${pkgName}/tmp/install-arch"
mkdir -p $tmpDir
cd $tmpDir

depends=("$pyPkg")
depends+=('python-gobject') ## The new gobject introspection
#depends+=('python-gflags')
depends+=('python-httplib2')
depends+=('python-psutil')
depends+=('python-dateutil')
depends+=('python-pymongo')
depends+=('python-cairo')

optdepends=()
optdepends+=('libappindicator-gtk3')
optdepends+=('python-dateutil')
optdepends+=('python-igraph')
#optdepends+=('python-gnomevfs')


depends_str=$(printf " '%s'" "${depends[@]}") ; depends_str=${depends_str:1}
optdepends_str=$(printf " '%s'" "${optdepends[@]}") ; optdepends_str=${optdepends_str:1}

echo "# Contributor: Saeed Rasooli <saeed.gnu@gmail.com>
# This is a local PKGBUILD
sourceDir='$sourceDir'
pkgname=$pkgName
pkgver=$version
pkgrel=1
pkgdesc='A full-featured international calendar written in Python'
arch=('any')
url=http://ilius.github.io/starcal
license=('GPLv3')
depends=($depends_str)
optdepends=($optdepends_str)
makedepends=()
conflicts=('starcal-git')
source=()
md5sums=()
package() {
	\"\$sourceDir/install\" \"\$pkgdir\" --for-pkg --python='$pyCmd'
}" > PKGBUILD

makepkg -sif

cp $pkgName*.pkg.tar* "$initPwd" || sudo cp $pkgName*.pkg.tar* "$initPwd" && echo "Package installed and copied into $initPwd directory"
cd "$initPwd"
rm -Rf $tmpDir

